shared:
  image: node:12
  steps:
    - ls
    
jobs:
  main:
    requires: [ ~commit ]
  sub1:
    requires: [ ~main ]
  sub2:
    requires: [ ~main ]
    steps:
      - exit 1
  join:
    requires: [ sub1, sub2 ]
